version: '3'

services:
  rabbit-local:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: order-status
      RABBITMQ_DEFAULT_PASS: rabbitmq-password
